@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Thu May 12 17:56:41 +0200 2022
=======
REM Generated by Vivado on Thu May 05 19:35:31 +0200 2022
>>>>>>> a9a44bfa2d7285a26cdd5bc0f4ecc4d6210cdf73
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: compile.bat
REM
REM ****************************************************************************
REM compile VHDL design sources
<<<<<<< HEAD
echo "xvhdl --incr --relax -prj Test_Shift_Moduke_V2_vhdl.prj"
call xvhdl  --incr --relax -prj Test_Shift_Moduke_V2_vhdl.prj -log xvhdl.log
=======
echo "xvhdl --incr --relax -prj TEST_JUMP_vhdl.prj"
call xvhdl  --incr --relax -prj TEST_JUMP_vhdl.prj -log xvhdl.log
>>>>>>> a9a44bfa2d7285a26cdd5bc0f4ecc4d6210cdf73
call type xvhdl.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
