@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< HEAD
REM Generated by Vivado on Thu May 12 17:56:42 +0200 2022
=======
REM Generated by Vivado on Thu May 05 19:35:33 +0200 2022
>>>>>>> a9a44bfa2d7285a26cdd5bc0f4ecc4d6210cdf73
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
<<<<<<< HEAD
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Test_Shift_Moduke_V2_behav xil_defaultlib.Test_Shift_Moduke_V2 -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Test_Shift_Moduke_V2_behav xil_defaultlib.Test_Shift_Moduke_V2 -log elaborate.log
=======
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TEST_JUMP_behav xil_defaultlib.TEST_JUMP -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TEST_JUMP_behav xil_defaultlib.TEST_JUMP -log elaborate.log
>>>>>>> a9a44bfa2d7285a26cdd5bc0f4ecc4d6210cdf73
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
